### ISSUE TITLE
Basis can't be a mix of Perms and MeshPatts

### ISSUE THREAD

**Issue by bjk17** [PermutaTriangle/Permuta#67]
Because `Perm`s and `MeshPatt`s can't be compared in sorting, a basis cannot consist of a mix of both object types. See below for example:

```python
>>> from permuta import *
>>> Av({Perm((0, 1)), MeshPatt(Perm((1, 0)), [])})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bjarni/.venvs/CombCov/lib/python3.7/site-packages/permuta/permset.py", line 99, in __new__
    return PermSet.avoiding(basis)
  File "/Users/bjarni/.venvs/CombCov/lib/python3.7/site-packages/permuta/permset.py", line 75, in avoiding
    return cls(BasisCls(basis))
  File "/Users/bjarni/.venvs/CombCov/lib/python3.7/site-packages/permuta/descriptors/basis.py", line 19, in __new__
    return tuple.__new__(cls).union(patts, cls.ALLOWED_BASIS_ELEMENT_TYPES)
  File "/Users/bjarni/.venvs/CombCov/lib/python3.7/site-packages/permuta/descriptors/basis.py", line 42, in union
    patts = sorted(patts)  # Necessarily non-empty
  File "/Users/bjarni/.venvs/CombCov/lib/python3.7/site-packages/permuta/perm.py", line 2215, in __lt__
    return (len(self), tuple(self)) < (len(other), tuple(other))
TypeError: object of type 'int' has no len()
```

Possible fixes includes
(1) implementing the comparator on the level of the abstract interface `Patt` so that `Perm`s and `MeshPatt`s can be compared or
(2) convert `Perm`s to `MeshPatt`s in the basis if at least one of the elements is a `MeshPatt`.

**Comment by christianbean** [comment]
It shouldn't. If Perm and MeshPatt are used, then all types should be MeshPatt in my opinion.

**Comment by bjk17** [comment]
Do you agree that `Av({Perm((0, 1)), MeshPatt(Perm((1, 0)), [])})` should be allowed and converted to `Av({MeshPatt(Perm((0, 1)), []), MeshPatt(Perm((1, 0)), [])})`?

**Comment by christianbean** [comment]
Yes, I agree.

**Comment by ulfarsson** [comment]
Sounds good and use MeshBasis?

**Comment by bjk17** [comment]
This was discussed in private and we came to the decision to change `MeshBasis` so it convert all its `Perm` elements to `MeshPatt`. That will eliminate the error above.
