### ISSUE TITLE
Problem with `sum_indecomposable_sequence`

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Permuta#85]
If you run this code 

```python
from permuta import Perm

p = Perm((0,1,2))
p.sum_indecomposable_sequence()
```

You get
```python
Traceback (most recent call last):
  File "bug.py", line 4, in <module>
    p.sum_indecomposable_sequence()
  File "/home/enadeau/repos/Permuta/permuta/perm.py", line 1744, in sum_indecomposable_sequence
    S = self.downset()
AttributeError: 'Perm' object has no attribute 'downset'
```

I'm  not sure what this function is supposed to do, but we should fix that.

**Comment by christianbean** [comment]
These were permpy functions.

One Perm there was
```python
def downset(self):
    return permset.PermSet([self]).downset()
```
which references the function on PermSet
```python
	def downset(self, return_class=False):
		"""Return the downset of `self` as a list.
		ME: TODO!
		"""
		bottom_edge = PermSet()
		bottom_edge.update(self)

		done = PermSet(bottom_edge)
		while len(bottom_edge) > 0:
			oldsize = len(done)
			next_layer = bottom_edge.layer_down()
			done.update(next_layer)
			del bottom_edge
			bottom_edge = next_layer
			del next_layer
			newsize = len(done)
			# print(f"\t\tDownset currently has {newsize} permutations, added {newsize-oldsize} in the last run.")
		if not return_class:
			return done
		cl = [PermSet([])]
		max_length = max([len(P) for P in done])
		for i in range(1,max_length+1):
			cl.append(PermSet([P for P in done if len(P) == i]))
		return cl
```
My feeling is this a reverse compatability issue, relating issue #47, and the method `sum_indecomposable_sequence` should be removed from the Perm object.

**Comment by christianbean** [comment]
Function removed in PR #100
